### ISSUE TITLE
Sav file timestamp string is invalid

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#197]
when reading test_2014.sav an error arises:

```
readstat-1.1.1$ ./readstat test_2014.sav
Format: SPSS binary file (SAV)
Invalid date string (length=9):  1-Jan- 5
Error processing test_2014.sav: The file's timestamp string is invalid
```

The file test_2014_working.sav reads correctly. 
Both files are opened correctly in SPSS 25.

[test_2014.zip](https://github.com/WizardMac/ReadStat/files/3906889/test_2014.zip)

**Comment by ofajardo** [comment]
hi

thanks a lot for fixing! I think that when you did the correction I tested and it was good (can't remember well now). However in the release 1.1.2 the issue seems to be still there:

```
(base) root@faa8dbc4f212:/myhome/Downloads/readstat-1.1.2# bin/bin/readstat ../test_2014/test_2014.sav
Format: SPSS binary file (SAV)
Invalid date string (length=9):  1-Jan- 5
Error processing ../test_2014/test_2014.sav: The file's timestamp string is invalid
```

**Comment by evanmiller** [comment]
Okay - I thought the issue was just the space-padding. But it's also the use of dashes instead of spaces. I will get this fixed in a future update.

**Comment by evanmiller** [comment]
Try the dev branch

https://github.com/WizardMac/ReadStat/commit/a71b4e80dae729e236d63d42066e79ca646cd23b

**Comment by ofajardo** [comment]
thanks that solves it!

**Comment by hmeleiro** [comment]
Hello! I'm having the same issue with a sav file. I'm using R `haven `library, but the error persists if I use directly `ReadStat` latest release (1.1.7). The file is correctly open in SPSS.

[3361.zip](https://github.com/WizardMac/ReadStat/files/8677248/3361.zip)
